let a = document.createElement("h3");
let b = document.createTextNode("Buy high quality organic fruits online");
a.append(b);
let divs = document.querySelectorAll("div");
divs[0].append(a);
let para  = document.createElement("p");
let text = document.createTextNode("Total fruits: 4");
para.append(text);
para.id = "fruits-total";
divs[1].append(para);
let h = document.getElementsByTagName("h3");
h[0].style.fontStyle = "italic";